### ISSUE TITLE
get_client + small query_limit

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/clickhouse-connect#123]
```
>>> client = clickhouse_connect.get_client(send_progress=False, compress=False , query_limit=5000)

>>> client = clickhouse_connect.get_client(send_progress=False, compress=False , query_limit=100)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/.local/lib/python3.8/site-packages/clickhouse_connect/__init__.py", line 8, in get_client
    return create_client(**kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/clickhouse_connect/driver/__init__.py", line 59, in create_client
    return HttpClient(interface, host, port, username, password, database, settings=settings, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/clickhouse_connect/driver/httpclient.py", line 160, in __init__
    comp_setting = self.server_settings['enable_http_compression']
KeyError: 'enable_http_compression'

```

and you use `query_limit` for internal queries, like `SELECT name, value, changed, description, type, readonly FROM system.settings limit 5000`

and BTW, I think you don't use `system.settings` column `description`.

**Comment by genzgd** [comment]
Good catch, I think that's the only "internal query" that we actually run but yeah that's broken

**Comment by genzgd** [comment]
I guess it could also affect getting table metadata.
