### ISSUE TITLE
query_df method fails parsing SimpleAggregateFuction(func, LowCardinality(String)) column

### ISSUE THREAD

**Issue by konst-ivanov** [ClickHouse/clickhouse-connect#182]
### Describe the bug
`Client.query_df` method fails parsing `SimpleAggregateFuction(func, LowCardinality(String))` column, but work fine with `SimpleAggregateFuction(func, String)`.

### Steps to reproduce
1. run ClickHouse locally
2. run code example provided

### Expected behaviour
Response successfully parsed to DataFrame

### Code example
```python
from clickhouse_connect import get_client


def main():
    db_conf = {
        "database": "default",
        "username": "user",
        "password": "pass",
        "host": "localhost",
        "port": 8123,
    }
    
    create_db = "CREATE DATABASE IF NOT EXISTS default"
    create_query = """
    CREATE TABLE IF NOT EXISTS default.simple_agg
    (
        id UInt32,
        str SimpleAggregateFunction(any, String),
        lc_str SimpleAggregateFunction(any, LowCardinality(String))
    )
    ENGINE AggregatingMergeTree()
    ORDER BY id"""
    insert_query = "INSERT INTO default.simple_agg VALUES (1, 'str', 'lc_str')"
    
    client = get_client(**db_conf)
    client.query(create_db)
    client.query(create_query)
    client.query(insert_query)
    str_df = client.query_df("SELECT str FROM default.simple_agg")
    lc_str_df = client.query_df("SELECT lc_str FROM default.simple_agg")
    

if __name__ == '__main__':
    main()
```

### clickhouse-connect and/or ClickHouse server logs
```
Traceback (most recent call last):
  File "/Users/user/PycharmProjects/ch_connect/clickhouse_connect_example.py", line 34, in <module>
    main()
  File "/Users/user/PycharmProjects/ch_connect/clickhouse_connect_example.py", line 30, in main
    lc_str_df = client.query_df("SELECT lc_str FROM public.simple_agg")
  File "/Users/user/PycharmProjects/ch_connect/venv/lib/python3.7/site-packages/clickhouse_connect/driver/client.py", line 314, in query_df
    res = self._context_query(locals(), use_numpy=True, as_pandas=True)
  File "/Users/user/PycharmProjects/ch_connect/venv/lib/python3.7/site-packages/clickhouse_connect/driver/client.py", line 674, in _context_query
    return self._query_with_context((self.create_query_context(**kwargs)))
  File "/Users/user/PycharmProjects/ch_connect/venv/lib/python3.7/site-packages/clickhouse_connect/driver/httpclient.py", line 217, in _query_with_context
    query_result = self._transform.parse_response(byte_source, context)
  File "/Users/user/PycharmProjects/ch_connect/venv/lib/python3.7/site-packages/clickhouse_connect/driver/transform.py", line 62, in parse_response
    first_block = get_block()
  File "/Users/user/PycharmProjects/ch_connect/venv/lib/python3.7/site-packages/clickhouse_connect/driver/transform.py", line 57, in get_block
    raise StreamFailureError(message) from None
clickhouse_connect.driver.exceptions.StreamFailureError: lc_str4SimpleAggregateFunction(any, LowCardinality(String))
```

#### Environment
* clickhouse-connect version: 0.5.20
* Python version: 3.7.9
* Operating system: macOS Monterey 12.1

#### ClickHouse server
* ClickHouse Server version: 22.3.13.80
* `CREATE TABLE` statements for tables involved: see code example

**Comment by genzgd** [comment]
Thanks for the detailed report and repro steps!  This should be fixed in the 0.5.23 version which will be released shortly.
