### ISSUE TITLE
`insert_df` method fails inserting `SimpleAggregateFunction(func, LowCardinality(String))` column

### ISSUE THREAD

**Issue by konst-ivanov** [ClickHouse/clickhouse-connect#187]
### Describe the bug
`Client.insert_df` method fails inserting `SimpleAggregateFunction(func, LowCardinality(String))` column.
Works fine for both `LowCardinality(String)` and `SimpleAggregateFunction(func, String)`.

### Steps to reproduce
1. run ClickHouse locally
2. run code example provided

### Expected behaviour
All inserts in the code example succeed

### Code example
```python
import pandas as pd
from clickhouse_connect import get_client


def main():
    db_conf = {
        "database": "public",
        "username": "user",
        "password": "pass",
        "host": "localhost",
        "port": 8123,
    }

    create_db = "CREATE DATABASE IF NOT EXISTS default"
    create_query = """
    CREATE TABLE IF NOT EXISTS default.sa_lc_insert
    (
        lc_str LowCardinality(String),
        sa_str SimpleAggregateFunction(any, String),
        sa_lc_str SimpleAggregateFunction(any, LowCardinality(String))
    )
    ENGINE AggregatingMergeTree()
    ORDER BY lc_str"""

    client = get_client(**db_conf)
    client.query(create_db)
    client.query(create_query)
    df = pd.DataFrame([['lc_str', 'sa_str', 'sa_lc_str']], columns=['lc_str', 'sa_str', 'sa_lc_str'])
    client.insert_df(df=df[['lc_str']], database='default', table='sa_lc_insert')
    print("LowCardinality has been successfully inserted.")
    client.insert_df(df=df[['sa_str']], database='default', table='sa_lc_insert')
    print("SimpleAggregateFunction with String has been successfully inserted.")
    client.insert_df(df=df[['sa_lc_str']], database='default', table='sa_lc_insert')
    print("SimpleAggregateFunction with LowCardinality has been successfully inserted.")


if __name__ == '__main__':
    main()
```

### clickhouse-connect and/or ClickHouse server logs
```
LowCardinality has been successfully inserted.
SimpleAggregateFunction with String has been successfully inserted.
Code: 117. DB::Exception: Invalid version for SerializationLowCardinality key column.: While executing Native. (INCORRECT_DATA) (version 22.3.13.80 (official build))

Traceback (most recent call last):
  File "/Users/user/PycharmProjects/ch_connect/clickhouse_connect_example.py", line 38, in <module>
    main()
  File "/Users/user/PycharmProjects/ch_connect/clickhouse_connect_example.py", line 33, in main
    client.insert_df(df=df[['sa_lc_str']], database='public', table='sa_lc_insert')
  File "/Users/user/PycharmProjects/ch_connect/venv/lib/python3.7/site-packages/clickhouse_connect/driver/client.py", line 569, in insert_df
    settings=settings, context=context)
  File "/Users/user/PycharmProjects/ch_connect/venv/lib/python3.7/site-packages/clickhouse_connect/driver/client.py", line 537, in insert
    self.data_insert(context)
  File "/Users/user/PycharmProjects/ch_connect/venv/lib/python3.7/site-packages/clickhouse_connect/driver/httpclient.py", line 253, in data_insert
    error_handler)
  File "/Users/user/PycharmProjects/ch_connect/venv/lib/python3.7/site-packages/clickhouse_connect/driver/httpclient.py", line 277, in raw_insert
    server_wait=False)
  File "/Users/user/PycharmProjects/ch_connect/venv/lib/python3.7/site-packages/clickhouse_connect/driver/httpclient.py", line 398, in _raw_request
    error_handler(response)
  File "/Users/user/PycharmProjects/ch_connect/venv/lib/python3.7/site-packages/clickhouse_connect/driver/httpclient.py", line 245, in error_handler
    self._error_handler(response)
  File "/Users/user/PycharmProjects/ch_connect/venv/lib/python3.7/site-packages/clickhouse_connect/driver/httpclient.py", line 324, in _error_handler
    raise OperationalError(err_str) if retried else DatabaseError(err_str) from None
clickhouse_connect.driver.exceptions.DatabaseError: :HTTPDriver for http://localhost:8123 returned response code 400)
 Code: 117. DB::Exception: Invalid version for SerializationLowCardinality key column.: While executing Native. (INCORRECT_DATA) (version 22.3.13.80 (official build))


Process finished with exit code 1
```

#### Environment
* clickhouse-connect version: 0.5.23
* Python version: 3.7.9
* Operating system: macOS Monterey 12.1

#### ClickHouse server
* ClickHouse Server version: 22.3.13.80
* `CREATE TABLE` statements for tables involved: see code example

**Comment by genzgd** [comment]
Thanks for the detailed report!  This should be fixed in 0.5.24.
