### ISSUE TITLE
Errors superset sql_lab on ARRAY JOIN array(LowCardinality(string))

### ISSUE THREAD

**Issue by Paulo456** [ClickHouse/clickhouse-connect#221]
In superset sql_lab we have an error "DB engine Error
base error: 'utf-8' codec can't decode byte 0xe7 in position 20: invalid continuation byte"
on sql query:
```
SELECT dt, platforms, uniq(user_id) as U_
FROM my_table
ARRAY JOIN platforms
WHERE dt >= toDate(now()) - 10
GROUP BY dt, platforms
LIMIT 1001
```
`CREATE TABLE my_table` statements:
platforms - array(LowCardinality(string))
dt -  Date 
user_id - Int64

If there is not much data, then everything works fine.
if we request data for a range of 10 days - the query fails with the specified error, if separately for each day from the range - everything works.

The same query in the same environment via clickhouse-sqlalchemy==0.1.10 works well.

### logs from superset celery worker:
clickhousedb://user:XXXXXXXXXX@my_host:8123/default
[2023-07-14 12:55:24,423: INFO/ForkPoolWorker-31] Query 860570: Running statement 1 out of 1
[2023-07-14 12:55:24,442: DEBUG/ForkPoolWorker-31] Parsing with sqlparse statement: SELECT dt,
platforms,
count(user_id) as U_
FROM my_table
ARRAY JOIN platforms
WHERE dt >= toDate(now()) - 10
GROUP BY dt, platforms
[2023-07-14 12:55:24,455: DEBUG/ForkPoolWorker-31] Parsing with sqlparse statement: SELECT dt,
platforms,
count(user_id) as U_
FROM my_table
ARRAY JOIN platforms
WHERE dt >= toDate(now()) - 10
GROUP BY dt, platforms
[2023-07-14 12:55:24,474: DEBUG/ForkPoolWorker-31] Query 860570: Running query: SELECT dt,
platforms,
count(user_id) as U_
FROM my_table
ARRAY JOIN platforms
WHERE dt >= toDate(now()) - 10
GROUP BY dt, platforms
LIMIT 1001
[2023-07-14 12:55:24,711: WARNING/ForkPoolWorker-31] Unexpected low cardinality version 8389723785365771522 reading type LowCardinality(String)
[2023-07-14 12:55:24,711: WARNING/ForkPoolWorker-31] Unexpected low cardinality version 7166460070899744768 reading type LowCardinality(String)
[2023-07-14 12:55:24,711: DEBUG/ForkPoolWorker-31] [36m[stats_logger] (timing) sqllab.query.time_executing_query | 250.276123046875 [0m
[2023-07-14 12:55:24,714: ERROR/ForkPoolWorker-31] Query 860570: <class 'UnicodeDecodeError'>
Traceback (most recent call last):
File "/app/superset/sql_lab.py", line 273, in execute_sql_statement
db_engine_spec.execute(cursor, sql, async_=True)
File "/app/superset/db_engine_specs/base.py", line 1261, in execute
raise cls.get_dbapi_mapped_exception(ex)
File "/app/superset/db_engine_specs/base.py", line 1259, in execute
cursor.execute(query)
File "/usr/local/lib/python3.8/site-packages/clickhouse_connect/dbapi/cursor.py", line 51, in execute
self.data = query_result.result_set
File "/usr/local/lib/python3.8/site-packages/clickhouse_connect/driver/query.py", line 254, in result_set
return self.result_rows
File "/usr/local/lib/python3.8/site-packages/clickhouse_connect/driver/query.py", line 272, in result_rows
for block in stream:
File "/usr/local/lib/python3.8/site-packages/clickhouse_connect/driver/common.py", line 195, in __next__
return next(self.gen)
File "/usr/local/lib/python3.8/site-packages/clickhouse_connect/driver/query.py", line 292, in _row_block_stream
for block in self._column_block_stream():
File "/usr/local/lib/python3.8/site-packages/clickhouse_connect/driver/transform.py", line 69, in gen
next_block = get_block()
File "/usr/local/lib/python3.8/site-packages/clickhouse_connect/driver/transform.py", line 35, in get_block
name = source.read_leb128_str()
File "clickhouse_connect/driverc/buffer.pyx", line 200, in clickhouse_connect.driverc.buffer.ResponseBuffer.read_leb128_str
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe7 in position 20: invalid continuation byte
[2023-07-14 12:55:24,714: DEBUG/ForkPoolWorker-31] Query 860570: 'utf-8' codec can't decode byte 0xe7 in position 20: invalid continuation byte
[2023-07-14 12:55:24,739: INFO/ForkPoolWorker-31] Task sql_lab.get_sql_results[ded270c0-bfb6-4678-bcb3-cae950820fe4] succeeded in 0.40017608366906643s: {'query_id': 860570, 'status': 'failed', 'error': 'base error: \'utf-8\' codec can\'t decode byte 0xe7 in position 20: invalid continuation byte', 'errors': [{'message': 'base error: \'utf-8\' codec can\'t decode byte 0xe7 in position 20: invalid continuation byte', 'error_type': 'GENERIC_DB_ENGINE_ERROR', 'level': 'error', 'extra': {...}}]}

### Configuration
* clickhouse-connect==0.6.6 and superset==2.0.1
* Python version: 3.8
* Operating system: Debian 10
* ClickHouse Server version: 22.3.12

**Comment by genzgd** [comment]
Is there a way you can reproduce this outside of Superset just using clickhouse-connect?

Also the fact that small queries work okay make me wonder if there is some compression issue with the somewhat older ClickHouse version.  Can you add 'compression=0' into your Superset connection string?

**Comment by genzgd** [comment]
i'm also slightly confused -- as far as I know clickhouse-connect 0.6.6 doesn't work with Superset 2.0.1, I think you have to use a 0.5.x version of clickhouse-connect because the EngineSpec was removed in 0.6.x

**Comment by Paulo456** [comment]
I tried the 0.5.0 version - an error also occurs. 
to use clickhouse-connect 0.6.6 , I just installed this version and then set up clickhousedb in the connection string, etc.

I tried to set up the connection string like this:
clickhousedb://user:passw@my_host:8123/default?compression=0
can't save with this setting:
ERROR: (builtins.NoneType) None
(Background on this error at: http://sqlalche.me/e/13/dbapi)


I'll try without superset reproduce just using clickhouse-connect

**Comment by genzgd** [comment]
Do you get the same low level error in 5.0?

I've found the bug with setting `compression=0` via SQLAlchemy, my apologies for that.   Please try `compress=0` instead and I'll get a fix in the next release.   I'll also try to reproduce with an artificial Array(LowCardinality(String)) dataset when I get time.

**Comment by Paulo456** [comment]
I installed version clickhouse-connect==0.5.25 and set "compress=0" - the result is the same with conn string:
clickhousedb://user:passw@my_host:8123/default?compress=0

"clickhousedb error: 'utf-8' codec can't decode byte 0xa3 in position 31: invalid start byte"

logs:
File "/usr/local/lib/python3.8/site-packages/clickhouse_connect/driver/query.py", line 279, in _row_block_stream
for block in self._column_block_stream():
File "/usr/local/lib/python3.8/site-packages/clickhouse_connect/driver/transform.py", line 69, in gen
next_block = get_block()
File "/usr/local/lib/python3.8/site-packages/clickhouse_connect/driver/transform.py", line 35, in get_block
name = source.read_leb128_str()
File "clickhouse_connect/driverc/buffer.pyx", line 190, in clickhouse_connect.driverc.buffer.ResponseBuffer.read_leb128_str
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa3 in position 31: invalid start byte
[2023-07-17 14:01:35,861: DEBUG/ForkPoolWorker-31] Query 860724: 'utf-8' codec can't decode byte 0xa3 in position 31: invalid start byte
[2023-07-17 14:01:35,880: INFO/ForkPoolWorker-31] Task sql_lab.get_sql_results[7066690f-c36e-4074-b27d-fb3ffd71c58a] succeeded in 11.021909698843956s: {'query_id': 860724, 'status': 'failed', 'error': 'clickhousedb error: \'utf-8\' codec can\'t decode byte 0xa3 in position 31: invalid start byte', 'errors': [{'message': 'clickhousedb error: \'utf-8\' codec can\'t decode byte 0xa3 in position 31: invalid start byte', 'error_type': 'GENERIC_DB_ENGINE_ERROR', 'level': 'error', 'extra': {...}}]}

**Comment by genzgd** [comment]
Thanks for your patience, at least that rules out compression.  Do you know how many rows you get back "successfully" before you start seeing the low cardinality error?

Also just to confirm, I assume all of your strings are stored in UTF-8 encodig.

**Comment by genzgd** [comment]
I had some time to debug this and reproduced it locally.  It turns out that before ClickHouse 22.9, sometimes the server would send a block with 0 rows and clickhouse-connect was not handling that correctly.   Thanks for the detailed report and the additional information, it's very much appreciated.

**Comment by Paulo456** [comment]
I confirm that the problem has been fixed. I have installed version 0.6.8

**Comment by genzgd** [comment]
Thanks for the follow up report, always appreciated.
