### ISSUE TITLE
unable to insert DateTime

### ISSUE THREAD

**Issue by centralhardware** [ClickHouse/clickhouse-connect#236]
```

ERROR:telethon.client.updates:Unhandled exception on handler
Traceback (most recent call last):
  File "/Users/alex/PycharmProjects/telegram_record_send_message_activity/venv/lib/python3.9/site-packages/telethon/client/updates.py", line 451, in _dispatch_update
    await callback(event)
  File "/Users/alex/PycharmProjects/telegram_record_send_message_activity/src/main.py", line 39, in handler
    clickhouse.insert('telegram_messages',data, ['date_time', 'message', 'chat'])
  File "/Users/alex/PycharmProjects/telegram_record_send_message_activity/venv/lib/python3.9/site-packages/clickhouse_connect/driver/client.py", line 553, in insert
    context.data = data
  File "/Users/alex/PycharmProjects/telegram_record_send_message_activity/venv/lib/python3.9/site-packages/clickhouse_connect/driver/insert.py", line 91, in data
    self.column_count = len(data[0])
TypeError: object of type 'datetime.datetime' has no len()
```

**Comment by genzgd** [comment]
It looks like you're inserting a single dimensional array.  The `data` argument must be a two dimensional array (or tuple).  For example, if you are inserting two rows, your `data` element should look like this:

```python
from datetime import datetime

data = [
    [datetime(2023, 9, 2, 10, 15, 22), 'This is message 2', 100],
    [datetime(2023, 9, 2, 12, 15, 00), 'This is message 1', 101]
]

client.insert('telegram_messages', data, ['date_time', 'message', 'chat'])
```

If you are inserting two rows, you still need to wrap the first row in an array:
```python
from datetime import datetime

data = [
    [datetime(2023, 9, 2, 10, 15, 22), 'This is message 2', 100],
]

client.insert('telegram_messages', data, ['date_time', 'message', 'chat'])
```

If that doesn't fix the problem please reopen this and include the value of the `data` field.

**Comment by centralhardware** [comment]
thanks
