### ISSUE TITLE
Queries with "like" are failing with AssertionError

### ISSUE THREAD

**Issue by Jishnu-Prakash-K** [ClickHouse/clickhouse-connect#24]
Getting the below error when using "like" in queries with some pattern `'%abc/def%'` When we do the same query with `like '%'` or ` like '%abc%' ` works fine. There is no error from clickhouse for any patterns, same query runs in clickhouse-cli .
`Query 100503: <class 'AssertionError'>
 Traceback (most recent call last):
   File "/app/superset/sql_lab.py", line 273, in execute_sql_statement
     db_engine_spec.execute(cursor, sql, async_=True)
   File "/app/superset/db_engine_specs/base.py", line 1261, in execute
     raise cls.get_dbapi_mapped_exception(ex)
   File "/app/superset/db_engine_specs/base.py", line 1259, in execute
     cursor.execute(query)
   File "/app/superset_home/.local/lib/python3.8/site-packages/clickhouse_connect/dbapi/cursor.py", line 45, in execute
     query_result = self.client.query(operation, parameters)
   File "/app/superset_home/.local/lib/python3.8/site-packages/clickhouse_connect/driver/httpclient.py", line 172, in query
     data_result = self.parse_response(response.content, use_none)
   File "/app/superset_home/.local/lib/python3.8/site-packages/clickhouse_connect/driver/native.py", line 39, in parse_response
     column, loc = col_type.read_native_column(source, loc, num_rows, use_none=use_none)
   File "/app/superset_home/.local/lib/python3.8/site-packages/clickhouse_connect/datatypes/base.py", line 109, in read_native_column
     loc = self.read_native_prefix(source, loc)
   File "/app/superset_home/.local/lib/python3.8/site-packages/clickhouse_connect/datatypes/base.py", line 96, in read_native_prefix
     assert v == low_card_version
 AssertionError
 2022-07-06 10:08:06,920:ERROR:superset.sql_lab:Query 100503: <class 'AssertionError'>
 Traceback (most recent call last):
   File "/app/superset/sql_lab.py", line 273, in execute_sql_statement
     db_engine_spec.execute(cursor, sql, async_=True)
   File "/app/superset/db_engine_specs/base.py", line 1261, in execute
     raise cls.get_dbapi_mapped_exception(ex)
   File "/app/superset/db_engine_specs/base.py", line 1259, in execute
     cursor.execute(query)
   File "/app/superset_home/.local/lib/python3.8/site-packages/clickhouse_connect/dbapi/cursor.py", line 45, in execute
     query_result = self.client.query(operation, parameters)
   File "/app/superset_home/.local/lib/python3.8/site-packages/clickhouse_connect/driver/httpclient.py", line 172, in query
     data_result = self.parse_response(response.content, use_none)
   File "/app/superset_home/.local/lib/python3.8/site-packages/clickhouse_connect/driver/native.py", line 39, in parse_response
     column, loc = col_type.read_native_column(source, loc, num_rows, use_none=use_none)
   File "/app/superset_home/.local/lib/python3.8/site-packages/clickhouse_connect/datatypes/base.py", line 109, in read_native_column
     loc = self.read_native_prefix(source, loc)
   File "/app/superset_home/.local/lib/python3.8/site-packages/clickhouse_connect/datatypes/base.py", line 96, in read_native_prefix
     assert v == low_card_version
 AssertionError
 [SupersetError(message='clickhousedb error: ', error_type=<SupersetErrorType.GENERIC_DB_ENGINE_ERROR: 'GENERIC_DB_ENGINE_ERROR'>, level=<ErrorLevel.ERROR: 'error'>, extra={'engine_name': 'ClickHouse Connect', 'issue_codes': [{'code': 1002, 'message': 'Issue 1002 - The database returned an unexpected error.'}]})]
 Traceback (most recent call last):
   File "/app/superset/views/base.py", line 208, in wraps
     return f(self, *args, **kwargs)
   File "/app/superset/utils/log.py", line 244, in wrapper
     value = f(*args, **kwargs)
   File "/app/superset/views/core.py", line 2415, in sql_json
     command_result: CommandResult = command.run()
   File "/app/superset/sqllab/command.py", line 114, in run
     raise ex
   File "/app/superset/sqllab/command.py", line 98, in run
     status = self._run_sql_json_exec_from_scratch()
   File "/app/superset/sqllab/command.py", line 151, in _run_sql_json_exec_from_scratch
     raise ex
   File "/app/superset/sqllab/command.py", line 146, in _run_sql_json_exec_from_scratch
     return self._sql_json_executor.execute(
   File "/app/superset/sqllab/sql_json_executer.py", line 111, in execute
     raise SupersetErrorsException(
 superset.exceptions.SupersetErrorsException: [SupersetError(message='clickhousedb error: ', error_type=<SupersetErrorType.GENERIC_DB_ENGINE_ERROR: 'GENERIC_DB_ENGINE_ERROR'>, level=<ErrorLevel.ERROR: 'error'>, extra={'engine_name': 'ClickHouse Connect', 'issue_codes': [{'code': 1002, 'message': 'Issue 1002 - The database returned an unexpected error.'}]})]
 2022-07-06 10:08:06,941:WARNING:superset.views.base:[SupersetError(message='clickhousedb error: ', error_type=<SupersetErrorType.GENERIC_DB_ENGINE_ERROR: 'GENERIC_DB_ENGINE_ERROR'>, level=<ErrorLevel.ERROR: 'error'>, extra={'engine_name': 'ClickHouse Connect', 'issue_codes': [{'code': 1002, 'message': 'Issue 1002 - The database returned an unexpected error.'}]})]`

**Comment by genzgd** [comment]
What is the actual query you are running?  Can you run the same using clickhouse-client using the JSON output format and show the column types returned?  This is a low level error in reading LowCardinality strings?  Can you create a small reproducible example?

**Comment by Jishnu-Prakash-K** [comment]
These are the returned types
`field1 String
field2 LowCardinality(String)
field3 LowCardinality(String) DEFAULT ''
field4 LowCardinality(String) DEFAULT ''`
and the issue is with field4 when we do like queries on it . Please note that when given `field4 LIKE '%'` or `field4 LIKE '%abc%'` , it works fine, the issue is only when a special character comes I think, because `field4 LIKE '%abc/cd%'` fails.

**Comment by genzgd** [comment]
I cannot reproduce this locally with any variant of LIKE.  What ClickHouse version are you using?  Are you using any aggregations in your query?

**Comment by Jishnu-Prakash-K** [comment]
Clickhouse version 21.3 

Yes we are doing group by 
But we are able to execute the same query through clickhouse-client

**Comment by genzgd** [comment]
Okay, it may be related to the older ClickHouse version which is out of support and not tested with ClickHouse Connect.  We only test with supported LTS versions starting with 21.8.  I will do some limited tests against 21.3 to try to reproduce.

**Comment by genzgd** [comment]
Unable to reproduce, no further information provided.
