### ISSUE TITLE
"OSError: [Errno 24] Too many open files" even with high limits

### ISSUE THREAD

**Issue by fridary** [ClickHouse/clickhouse-connect#241]
I asked this question on official clickhouse github and was said, that it's python error, not clickhouse:
https://github.com/ClickHouse/ClickHouse/issues/54652

**OS:** Ubuntu 20.04.6 LTS
**ClickHouse:** 23.7.2.25 (official build)
**Server:** Intel(R) Xeon(R) CPU E5-2695 v4 @ 2.10GHz 72 cores
**clickhouse-connect version:** 0.6.11
**Python version:** 3.9.17

I read these topics about "Too many files open":
https://github.com/ClickHouse/ClickHouse/issues/8121
https://github.com/ClickHouse/ClickHouse/issues/14574

Error:
```
Traceback (most recent call last):
  File "/home/sirjay/miniconda3/envs/yolo/lib/python3.9/site-packages/clickhouse_connect/driver/httpclient.py", line 408, in _raw_request
  File "/home/sirjay/miniconda3/envs/yolo/lib/python3.9/site-packages/urllib3/request.py", line 78, in request
  File "/home/sirjay/miniconda3/envs/yolo/lib/python3.9/site-packages/urllib3/request.py", line 170, in request_encode_body
  File "/home/sirjay/miniconda3/envs/yolo/lib/python3.9/site-packages/urllib3/poolmanager.py", line 376, in urlopen
  File "/home/sirjay/miniconda3/envs/yolo/lib/python3.9/site-packages/urllib3/connectionpool.py", line 826, in urlopen
  File "/home/sirjay/miniconda3/envs/yolo/lib/python3.9/site-packages/urllib3/connectionpool.py", line 798, in urlopen
  File "/home/sirjay/miniconda3/envs/yolo/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8123): Max retries exceeded with url: /?wait_end_of_query=1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f39b1acca00>: Failed to establish a new connection: [Errno 24] Too many open files'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/www/mysite/task.py", line 93, in _return_task
    cl_client = clickhouse_connect.get_client(**db_config_clickhouse)
  File "/home/sirjay/miniconda3/envs/yolo/lib/python3.9/site-packages/clickhouse_connect/__init__.py", line 8, in get_client
  File "/home/sirjay/miniconda3/envs/yolo/lib/python3.9/site-packages/clickhouse_connect/driver/__init__.py", line 110, in create_client
  File "/home/sirjay/miniconda3/envs/yolo/lib/python3.9/site-packages/clickhouse_connect/driver/httpclient.py", line 140, in __init__
  File "/home/sirjay/miniconda3/envs/yolo/lib/python3.9/site-packages/clickhouse_connect/driver/client.py", line 60, in __init__
  File "/home/sirjay/miniconda3/envs/yolo/lib/python3.9/site-packages/clickhouse_connect/driver/httpclient.py", line 331, in command
  File "/home/sirjay/miniconda3/envs/yolo/lib/python3.9/site-packages/clickhouse_connect/driver/httpclient.py", line 419, in _raw_request
clickhouse_connect.driver.exceptions.OperationalError: Error HTTPConnectionPool(host='127.0.0.1', port=8123): Max retries exceeded with url: /?wait_end_of_query=1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f39b1acca00>: Failed to establish a new connection: [Errno 24] Too many open files')) executing HTTP request attempt 0 http://127.0.0.1:8123

2023-09-14 20:04:11,712 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc611cb9b80>: Failed to establish a new connection: [Errno 24] Too many open files')': /?wait_end_of_query=1
2023-09-14 20:04:11,713 WARNING Unexpected Http Driver Exception
2023-09-14 20:04:11,714 ERROR Traceback (most recent call last):
  File "/home/sirjay/miniconda3/envs/yolo/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
  File "/home/sirjay/miniconda3/envs/yolo/lib/python3.9/site-packages/urllib3/util/connection.py", line 95, in create_connection
  File "/home/sirjay/miniconda3/envs/yolo/lib/python3.9/site-packages/urllib3/util/connection.py", line 76, in create_connection
  File "/home/sirjay/miniconda3/envs/yolo/lib/python3.9/socket.py", line 232, in __init__
OSError: [Errno 24] Too many open files
```

I use clickhouse only for `insert` command with load ~10 operations/second. After 1 hour of work server sends the error above.

Info:
```
$ sysctl fs.file-max
fs.file-max = 300000
$ ulimit -Hn
100000
$ ulimit -Sn
100000
$ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 772764
max locked memory       (kbytes, -l) 65536
max memory size         (kbytes, -m) unlimited
open files                      (-n) 100000
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 772764
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
$ ps -ef|grep click
sirjay      7754       1  0 16:51 ?        00:00:00 clickhouse-watchdog        --config=/etc/clickhouse-server/config.xml --pid-file=/run/clickhouse-server/clickhouse-server.pid
sirjay      9047    7754 15 16:51 ?        00:30:05 /usr/bin/clickhouse-server --config=/etc/clickhouse-server/config.xml --pid-file=/run/clickhouse-server/clickhouse-server.pid
sirjay     42586   15650  0 20:08 pts/1    00:00:00 grep --color=auto click
$ more /proc/9047/limits
Limit                     Soft Limit           Hard Limit           Units     
Max cpu time              unlimited            unlimited            seconds   
Max file size             unlimited            unlimited            bytes     
Max data size             unlimited            unlimited            bytes     
Max stack size            8388608              unlimited            bytes     
Max core file size        1073741824           unlimited            bytes     
Max resident set          unlimited            unlimited            bytes     
Max processes             772764               772764               processes 
Max open files            500000               500000               files     
Max locked memory         65536                65536                bytes     
Max address space         unlimited            unlimited            bytes     
Max file locks            unlimited            unlimited            locks     
Max pending signals       772764               772764               signals   
Max msgqueue size         819200               819200               bytes     
Max nice priority         0                    0                    
Max realtime priority     0                    0                    
Max realtime timeout      unlimited            unlimited            us 
```

When I reboot server I get this:
```
$ cat /proc/sys/fs/file-nr
33872	0	300000
```

After 1 hour of work and getting errors:
```
$ cat /proc/sys/fs/file-nr
57488	0	300000
--^-------------------
this must be total opened files
```

What is mistake?
And the most important, why number of files in the system increases so fast? In 1 day there can be 24*57488=1.3 million of files?

database has 1 table:
```
CREATE TABLE test_table
(
    datetime  DateTime64(3) NOT NULL DEFAULT now(),
    user_id  UInt32 NOT NULL,
    var1  String NOT NULL,
    var2  String NOT NULL,
    num1  Float32 NOT NULL,
    num2  Int8 NOT NULL,
    num3  UInt32 NOT NULL DEFAULT 0,
    num4  Decimal64(3) NOT NULL
)
ENGINE = MergeTree()
PRIMARY KEY (user_id, (user_id, var1), (num3, var1), num3);
```
Maybe I set wrong indexes/primary key?

**Comment by genzgd** [comment]
Are you running ClickHouse on the same server as `clickhouse-connect`?   How are you doing 10 inserts per second?  Are you inserting one row at a time?

**Comment by genzgd** [comment]
Also you only get one primary key and there are no secondary indexes (there are skip indexes, which a much different).  In your case it probably should just be (user_id) or (user_id, datetime).  Whatever you are doing with multiple tuples in the primary key is definitely not what you want.

**Comment by fridary** [comment]
As @den-crane recommended me here https://github.com/ClickHouse/ClickHouse/issues/54652, I checked `/var/log/clickhouse-server/clickhouse-server.err.log` and there were no `[Errno 24] Too many open files` indeed. So it seems it's really python error.

But, I can see quantity of files in system raise dramatically. Is this okey or something goes wrong? I was making 30 inserts per second and result after 20 minutes:

```
$ ulimit -Hn
100000
$ ulimit -Sn
100000
$ cat /proc/sys/fs/file-nr
45637 0 300000
$ find /var/lib/clickhouse -type f | wc -l
63172
$ find /var/lib/clickhouse -type f | wc -l
67081
$ find /var/lib/clickhouse -type f | wc -l
74703
$ cat /proc/sys/fs/file-nr
48720 0 300000
$ find /var/lib/clickhouse -type f | wc -l
122783
$ cat /proc/sys/fs/file-nr
52176 0 300000
$ find /var/lib/clickhouse -type f | wc -l
158806
$ cat /proc/sys/fs/file-nr
55920 0 300000
$ find /var/lib/clickhouse -type f | wc -l
200258
$ cat /proc/sys/fs/file-nr
59520 0 300000
$ find /var/lib/clickhouse -type f | wc -l
204218
$ cat /proc/sys/fs/file-nr
63696 0 300000
$ find /var/lib/clickhouse -type f | wc -l
202974
$ cat /proc/sys/fs/file-nr
87168 0 300000
$ find /var/lib/clickhouse -type f | wc -l
154666
$ find /var/lib/clickhouse -type f | wc -l
94656 0 300000

.. now Too many open files error raises ..
```

after getting errors, I stopped all inserts and got this:
```
$ find /var/lib/clickhouse -type f | wc -l
18871
$ find /var/lib/clickhouse -type f | wc -l
95564 0 300000
```



> Are you running ClickHouse on the same server as `clickhouse-connect`? How are you doing 10 inserts per second? Are you inserting one row at a time?

Yes, I'm running clickhouse and python script on the same server. Inserts I do on every iteration (10-30 inserts per second, each time new connection `get_client()`, because else I got another errors about the using same sessions):
```python
cl_client = clickhouse_connect.get_client(**db_config)
cl_client.insert('table', data, column_names=['datetime', 'id', ...])
```

@genzgd any ideas what can be wrong?

**Comment by genzgd** [comment]
You should do fewer inserts per second.  I believe your insert rate is causing both the ClickHouse and clickhouse connect to use a large number file handles (ClickHouse is using them for small data part files, `clickhouse-connect` is using some for HTTP connections).  The original recommendation was one insert per second on a ClickHouse table, although it can go higher on newer system.  In general you should insert thousands of rows in single insert rather than many smaller inserts.

You should also try just using one clickhouse-connect client rather than a new one every time.  See [here](https://clickhouse.com/docs/en/integrations/python#managing-clickhouse-session-ids) for ways to avoid the session id problem.  In particular, try this before calling `get_client`:

```python
from clickhouse_connect import common

common.set_setting('autogenerate_session_id', False)  # This should always be set before creating a client
```

**Comment by fridary** [comment]
@genzgd it seems problems solved with this `common.set_setting('autogenerate_session_id', False)`. Very weird, because I remember it was written in documentation that I should create each session new id.
