### ISSUE TITLE
insert_df() raises a TypeErroro of int() while the Enum value is None

### ISSUE THREAD

**Issue by zhuoluoy** [ClickHouse/clickhouse-connect#256]
### Steps to reproduce
```python
x.BSFlag = None
client.insert_df('tick_market_data', x)
```

```
x.BSFlag = None
x.BSFlag
Out[34]: 
0    None
Name: BSFlag, dtype: object
x
Out[35]: 
        Date      Time  Price  ...  Volume Turnover  Return
0 2023-06-30  91403000    0.0  ...     0.0      0.0     0.0
[1 rows x 45 columns]
self.client.insert_df('tick_market_data', x)
2023-10-23 10:55:22,290 - clickhouse_connect.driver.transform - 13962 - ERROR - Error serializing column `BSFlag` into into data type `Enum8('B' = 1, 'S' = 2)`
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/clickhouse_connect/driver/transform.py", line 102, in chunk_gen
    col_type.write_column(data, output, context)
  File "/usr/local/lib/python3.9/site-packages/clickhouse_connect/datatypes/base.py", line 202, in write_column
    self.write_column_data(column, dest, ctx)
  File "/usr/local/lib/python3.9/site-packages/clickhouse_connect/datatypes/base.py", line 217, in write_column_data
    self._write_column_binary(column, dest, ctx)
  File "/usr/local/lib/python3.9/site-packages/clickhouse_connect/datatypes/numeric.py", line 226, in _write_column_binary
    write_array(self._array_type, column, dest)
  File "/usr/local/lib/python3.9/site-packages/clickhouse_connect/driver/common.py", line 52, in write_array
    column = [int(x) for x in column]
  File "/usr/local/lib/python3.9/site-packages/clickhouse_connect/driver/common.py", line 52, in <listcomp>
    column = [int(x) for x in column]
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3505, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-36-3cb5e42a205a>", line 1, in <module>
    self.client.insert_df('tick_market_data', x)
  File "/usr/local/lib/python3.9/site-packages/clickhouse_connect/driver/client.py", line 585, in insert_df
    return self.insert(table,
  File "/usr/local/lib/python3.9/site-packages/clickhouse_connect/driver/client.py", line 554, in insert
    return self.data_insert(context)
  File "/usr/local/lib/python3.9/site-packages/clickhouse_connect/driver/httpclient.py", line 250, in data_insert
    response = self._raw_request(block_gen, params, headers, error_handler=error_handler, server_wait=False)
  File "/usr/local/lib/python3.9/site-packages/clickhouse_connect/driver/httpclient.py", line 431, in _raw_request
    error_handler(response)
  File "/usr/local/lib/python3.9/site-packages/clickhouse_connect/driver/httpclient.py", line 235, in error_handler
    raise ex
  File "/usr/local/lib/python3.9/site-packages/clickhouse_connect/driver/transform.py", line 102, in chunk_gen
    col_type.write_column(data, output, context)
  File "/usr/local/lib/python3.9/site-packages/clickhouse_connect/datatypes/base.py", line 202, in write_column
    self.write_column_data(column, dest, ctx)
  File "/usr/local/lib/python3.9/site-packages/clickhouse_connect/datatypes/base.py", line 217, in write_column_data
    self._write_column_binary(column, dest, ctx)
  File "/usr/local/lib/python3.9/site-packages/clickhouse_connect/datatypes/numeric.py", line 226, in _write_column_binary
    write_array(self._array_type, column, dest)
  File "/usr/local/lib/python3.9/site-packages/clickhouse_connect/driver/common.py", line 52, in write_array
    column = [int(x) for x in column]
  File "/usr/local/lib/python3.9/site-packages/clickhouse_connect/driver/common.py", line 52, in <listcomp>
    column = [int(x) for x in column]
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

### Expected behaviour

A NULL value should be inserted.

### Code example
```python
x.BSFlag = None
client.insert_df('tick_market_data', x)
```

BSFlag is an Enum8.

**Comment by zhuoluoy** [comment]
https://github.com/ClickHouse/clickhouse-connect/blob/15e88b2056d6f1cd53ffbc5094187c4de85db3ab/clickhouse_connect/driver/common.py#L52

I think the problem is here. The int(x) coversion didn't consider the None(Python)->NULL(SQL) situation.

**Comment by genzgd** [comment]
I can't reproduce this.  Is BSFlag an Enum8 or is it a Nullable(Enum8)?  ClickHouse columns are "NOT NULL" by default.

**Comment by zhuoluoy** [comment]
The BSFlag is an Enum8.
However, I can use SQL to insert a NULL value.
```sql
INSERT INTO tick_market_data(BSFlag) VALUES(NULL);
```
It's strange.

**Comment by zhuoluoy** [comment]
![image](https://github.com/ClickHouse/clickhouse-connect/assets/656810/db3e5cad-3055-4bfc-b87c-c19afa8424de)

**Comment by genzgd** [comment]
`clickhouse client` apparently converts the NULL value into a `0` int value, which is not always a valid enum value.  For example: 

```sql
CREATE TABLE test
(
    `key` Int32,
    `value` Enum('one' = 1)
)
ENGINE = MergeTree
ORDER BY key;

Query id: 7d39e716-599e-4093-ae80-4bf9725a5fbb

Ok.

INSERT INTO test VALUES(1, NULL);

INSERT INTO fred FORMAT Values

Query id: 358ea033-0a68-42be-b253-0edc11744adc

Ok.

1 row in set. Elapsed: 0.003 sec. 

SELECT *
FROM test

Query id: b473fe6e-5e64-447c-9dee-7379102d3344

Ok.
Exception on client:
Code: 36. DB::Exception: Code: 36. DB::Exception: Unexpected value 0 in enum. (BAD_ARGUMENTS) (version 23.8.1.2950 (official build)). (BAD_ARGUMENTS)
```

If you want an actual NULL value you should create a Nullable(Enum8) column.  I don't think it's safe or desirable to automatically convert Python `None` to a `0` value in `clickhouse-connect`

**Comment by zhuoluoy** [comment]
> I can't reproduce this. Is BSFlag an Enum8 or is it a Nullable(Enum8)? ClickHouse columns are "NOT NULL" by default.

Yeah.
I tried to modify the column as a Nullabe(Enum). The problem is fixed.
Thank you so much.
