### ISSUE TITLE
Unable to connect optimized C data functions [No module named 'clickhouse_connect.driverc.buffer'], falling back to pure Python

### ISSUE THREAD

**Issue by cosinus90** [ClickHouse/clickhouse-connect#284]
Getting this error on this line

`import clickhouse_connect`

Ubuntu 18.04.6 LTS
Python 3.7.5
clickhouse_connect Version: 0.6.23

pip3 show lz4
Name: lz4
Version: 4.3.2

`
Unable to connect optimized C data functions [No module named 'clickhouse_connect.driverc.buffer'], falling back to pure Python
Traceback (most recent call last):
  File "sync-subscriptions.py", line 1, in <module>
    import clickhouse_connect
  File "/usr/local/lib/python3.8/dist-packages/clickhouse_connect/__init__.py", line 1, in <module>
    from clickhouse_connect.driver import create_client
  File "/usr/local/lib/python3.8/dist-packages/clickhouse_connect/driver/__init__.py", line 9, in <module>
    from clickhouse_connect.driver.httpclient import HttpClient
  File "/usr/local/lib/python3.8/dist-packages/clickhouse_connect/driver/httpclient.py", line 20, in <module>
    from clickhouse_connect.driver.compression import available_compression
  File "/usr/local/lib/python3.8/dist-packages/clickhouse_connect/driver/compression.py", line 5, in <module>
    import lz4
  File "/usr/local/lib/python3.8/dist-packages/lz4/__init__.py", line 14, in <module>
    from ._version import (  # noqa: F401
ModuleNotFoundError: No module named 'lz4._version'
`

uninstall/install lz4 not helped.

**Comment by genzgd** [comment]
Python 3.7 is not supported.  However, your stack trace indicates `clickhouse-connect` is installed under 3.8, and your lz4 installation is broken somehow?

**Comment by genzgd** [comment]
No additional details provided; this appears to a Python environment issue.
