### ISSUE TITLE
Clickhouse python client does not cast numbers on insertion 

### ISSUE THREAD

**Issue by ahnazary** [ClickHouse/clickhouse-connect#292]
### Describe the bug
When inserting numbers into a clickhouse table, clickhouse can cast numbers to match them with the datatype of the target table column, for example if you try to insert a `Float` value into a column with `Int` datatype, clickhouse will cast the `Float` to `Int` (numbers after decimal will be removed though) and server carries out the insertion without any error, but this casting does not happen when insertion happens by using the clickhouse python client and it exists with an error. 

Below is the full error message you will see if you try to insert a `float` into a column with `Int` datatype:

```
Error serializing column `num_col` into data type `Int32`
Traceback (most recent call last):
  File "/Users/amirnazary/anaconda3/envs/development/lib/python3.11/site-packages/clickhouse_connect/driver/common.py", line 55, in write_array
    dest += buff.pack(*column)
            ^^^^^^^^^^^^^^^^^^
struct.error: required argument is not an integer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/amirnazary/anaconda3/envs/development/lib/python3.11/site-packages/clickhouse_connect/driver/transform.py", line 102, in chunk_gen
    col_type.write_column(data, output, context)
  File "/Users/amirnazary/anaconda3/envs/development/lib/python3.11/site-packages/clickhouse_connect/datatypes/base.py", line 202, in write_column
    self.write_column_data(column, dest, ctx)
  File "/Users/amirnazary/anaconda3/envs/development/lib/python3.11/site-packages/clickhouse_connect/datatypes/base.py", line 217, in write_column_data
    self._write_column_binary(column, dest, ctx)
  File "/Users/amirnazary/anaconda3/envs/development/lib/python3.11/site-packages/clickhouse_connect/datatypes/base.py", line 341, in _write_column_binary
    write_array(self._array_type, column, dest)
  File "/Users/amirnazary/anaconda3/envs/development/lib/python3.11/site-packages/clickhouse_connect/driver/common.py", line 57, in write_array
    raise DataError('Unable to create Python array.  This is usually caused by trying to insert None ' +
clickhouse_connect.driver.exceptions.DataError: Unable to create Python array.  This is usually caused by trying to insert None values into a ClickHouse column that is not Nullable
Traceback (most recent call last):
  File "/Users/amirnazary/anaconda3/envs/development/lib/python3.11/site-packages/clickhouse_connect/driver/common.py", line 55, in write_array
    dest += buff.pack(*column)
            ^^^^^^^^^^^^^^^^^^
struct.error: required argument is not an integer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/amirnazary/Documents/Code/dbt/local_dbs/test.py", line 11, in <module>
    client.insert(table="test", data=data)
  File "/Users/amirnazary/anaconda3/envs/development/lib/python3.11/site-packages/clickhouse_connect/driver/client.py", line 554, in insert
    return self.data_insert(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amirnazary/anaconda3/envs/development/lib/python3.11/site-packages/clickhouse_connect/driver/httpclient.py", line 250, in data_insert
    response = self._raw_request(block_gen, params, headers, error_handler=error_handler, server_wait=False)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amirnazary/anaconda3/envs/development/lib/python3.11/site-packages/clickhouse_connect/driver/httpclient.py", line 431, in _raw_request
    error_handler(response)
  File "/Users/amirnazary/anaconda3/envs/development/lib/python3.11/site-packages/clickhouse_connect/driver/httpclient.py", line 235, in error_handler
    raise ex
  File "/Users/amirnazary/anaconda3/envs/development/lib/python3.11/site-packages/clickhouse_connect/driver/transform.py", line 102, in chunk_gen
    col_type.write_column(data, output, context)
  File "/Users/amirnazary/anaconda3/envs/development/lib/python3.11/site-packages/clickhouse_connect/datatypes/base.py", line 202, in write_column
    self.write_column_data(column, dest, ctx)
  File "/Users/amirnazary/anaconda3/envs/development/lib/python3.11/site-packages/clickhouse_connect/datatypes/base.py", line 217, in write_column_data
    self._write_column_binary(column, dest, ctx)
  File "/Users/amirnazary/anaconda3/envs/development/lib/python3.11/site-packages/clickhouse_connect/datatypes/base.py", line 341, in _write_column_binary
    write_array(self._array_type, column, dest)
  File "/Users/amirnazary/anaconda3/envs/development/lib/python3.11/site-packages/clickhouse_connect/driver/common.py", line 57, in write_array
    raise DataError('Unable to create Python array.  This is usually caused by trying to insert None ' +
clickhouse_connect.driver.exceptions.DataError: Unable to create Python array.  This is usually caused by trying to insert None values into a ClickHouse column that is not Nullable
```

### Steps to reproduce
1. setup a clickhouse server locally (e.g. with docker compose like below:)
```
version: '3'
services:
  clickhouse:
    image: yandex/clickhouse-server
    ports:
      - 8123:8123
      - 9000:9000
    volumes:
      - ./data:/var/lib/clickhouse
```
 
and spin-up the clickhosue server with `docker-compose up`

2. create a table called test with the following structure in clickhouse default database:
```
create table if not exists test (
	id Int32,
	num_col Int32
) Engine = MergeTree
order by id
```

3.  run the following python code to try to execute an insert query:
```
from clickhouse_connect.driver import create_client

client = create_client(
    host = "localhost",
    port = 8123,
    password="",
    username="",
)

data = [(1, 7.234)]
client.insert(table="test", data=data)
```

This will result in the error mentioned above (the error is also not clear in my opinion), while if you try to insert the same row directly by executing sql query on clickhosue server, it will be executed without error:

#### sql query to execute on server:
```
insert into test (id, num_col) values (1, 7.234)
```

### Expected behaviour

The query should be execute without error and a row with values `(1, 7)` (after converting 7.234(`Float`) to 7(`Int32`) ) should appear in the `test` table. 

#### Environment
* clickhouse-connect version: `clickhouse-connect==0.6.23`
* Python version: 3.11.4
* Operating system: macOs

#### ClickHouse server
* ClickHouse Server version: `22.1.3.7`
* `CREATE TABLE` statements for tables involved:
```
create table if not exists test (
	id Int32,
	num_col Int32
) Engine = MergeTree
order by id
```

**Comment by genzgd** [comment]
In general I don't think it's good practice to silently change data to match the data type of the table column.  It's normally the caller's responsibility to convert the data to the correct type.  While the example you create does work using the ClickHouse cli client, it doesn't work in standard language clients like `clickhouse-java` or the `clickhouse-driver` Python client. 

To achieve what you want, you can use a list comprehension or otherwise convert the data before calling insert, which will have the same performance impact as doing it "automatically" in the driver, while leaving control with the application.  Silent data coercion also may hide bugs in the client application that will be difficult to debug.

**Comment by ahnazary** [comment]
Ok, thanks for the explanation @genzgd.
