### ISSUE TITLE
The problem with initializing an object to work with CH at the stage of getting server settings

### ISSUE THREAD

**Issue by mister-proger** [ClickHouse/clickhouse-connect#320]
### Describe the bug
ClickHouse used to be on my personal computer, along with all the other databases that we use for development. Everything we tested ran the same way on my computer, and no problems were observed. Now, I had to transfer the system disk with all the programs and data to the laptop. Since, of course, it cannot support many heavy processes, I ran only PSQL (native patch) and ClickHouse (in WSL) on it, just like it was on the last computer. I run the programs myself on another laptop using a VPN network for connect.
Yesterday I started testing the part of the code that works with CH again. I found that the initialization of the object takes too long. Experimentally, I found a line of code with a problem on `driver/client`:
```Python
server_settings = self.query(f'SELECT name, value, {readonly} as readonly FROM system.settings LIMIT 10000')
```
If you set the `LIMIT` to less than ~20, then of course not all the settings are obtained, but at least the object is initialized. Otherwise:
```cmd
Traceback (most recent call last):
  File "C:\Users\niels.MSI\Projects\DLB\venv\Lib\site-packages\urllib3\response.py", line 737, in _error_catcher
    yield
  File "C:\Users\niels.MSI\Projects\DLB\venv\Lib\site-packages\urllib3\response.py", line 1187, in read_chunked
    chunk = self._handle_chunk(amt)
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\niels.MSI\Projects\DLB\venv\Lib\site-packages\urllib3\response.py", line 1138, in _handle_chunk
    returned_chunk = self._fp._safe_read(self.chunk_left)  # type: ignore[union-attr]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\niels.MSI\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 633, in _safe_read
    data = self.fp.read(amt)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\niels.MSI\AppData\Local\Programs\Python\Python312\Lib\socket.py", line 707, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [WinError 10054] The remote host forcibly terminated an existing connection

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\niels.MSI\Projects\DLB\.print.py", line 8, in <module>
    connection = clickhouse_connect.get_client(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\niels.MSI\Projects\DLB\venv\Lib\site-packages\clickhouse_connect\driver\__init__.py", line 111, in create_client
    return HttpClient(interface, host, port, username, password, database, settings=settings, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\niels.MSI\Projects\DLB\venv\Lib\site-packages\clickhouse_connect\driver\httpclient.py", line 144, in __init__
    super().__init__(database=database,
  File "C:\Users\niels.MSI\Projects\DLB\venv\Lib\site-packages\clickhouse_connect\driver\client.py", line 72, in __init__
    server_settings = self.query(f'SELECT name, value, {readonly} as readonly FROM system.settings LIMIT 10000')
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\niels.MSI\Projects\DLB\venv\Lib\site-packages\clickhouse_connect\driver\client.py", line 195, in query
    return self._query_with_context(query_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\niels.MSI\Projects\DLB\venv\Lib\site-packages\clickhouse_connect\driver\httpclient.py", line 222, in _query_with_context
    query_result = self._transform.parse_response(byte_source, context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\niels.MSI\Projects\DLB\venv\Lib\site-packages\clickhouse_connect\driver\transform.py", line 68, in parse_response
    first_block = get_block()
                  ^^^^^^^^^^^
  File "C:\Users\niels.MSI\Projects\DLB\venv\Lib\site-packages\clickhouse_connect\driver\transform.py", line 33, in get_block
    num_cols = source.read_leb128()
               ^^^^^^^^^^^^^^^^^^^^
  File "clickhouse_connect\\driverc\\buffer.pyx", line 213, in clickhouse_connect.driverc.buffer.ResponseBuffer.read_leb128
  File "clickhouse_connect\\driverc\\buffer.pyx", line 101, in clickhouse_connect.driverc.buffer.ResponseBuffer._read_byte_load
  File "C:\Users\niels.MSI\Projects\DLB\venv\Lib\site-packages\urllib3\response.py", line 1040, in stream
    yield from self.read_chunked(amt, decode_content=decode_content)
  File "C:\Users\niels.MSI\Projects\DLB\venv\Lib\site-packages\urllib3\response.py", line 1172, in read_chunked
    with self._error_catcher():
  File "C:\Users\niels.MSI\AppData\Local\Programs\Python\Python312\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(value)
  File "C:\Users\niels.MSI\Projects\DLB\venv\Lib\site-packages\urllib3\response.py", line 764, in _error_catcher
    raise ProtocolError(f"Connection broken: {e!r}", e) from e
urllib3.exceptions.Protocol Error: ("Connection broken: ConnectionResetError(10054, 'Remote host forcibly terminated existing connection', None, 10054, None)", ConnectionResetError(10054, 'Remote host forcibly terminated existing connection', None, 10054, None))
```
(There may be inaccuracies in the description of the exceptions, I translated them into English)
I thought there was a problem with the VPN network, but PSQL calmly gave me the data. Then I specified `LIMIT 0` in the library - all `INSERT` requests via `connection.command` worked fine. 
However, `SELECT` via `connection.query` still refused to work, as soon as I exceeded a certain data threshold (I never found it, but here is an example for a table with three rows):
```Python
# CREATE OR REPLACE TABLE channels.messages (
#     `channel` UInt64,
#     `id` UInt64,
#     `version` UInt64,
#     `timestamp` DateTime64(6, 'UTC'),
#     `author` UInt64,
#     `type` Enum ('text' = 1, 'voice' = 2, 'video' = 3),
#     `data` String,
#     `files` Array (UInt64),
#     `media` Array (Array (UInt64)),
#     `is forward` Bool,
#     `forward type` Enum ('no' = 0, 'channel message' = 1),
#     `forward by` Array (UInt64),
#     `is deleted` Bool,
#     `deleted reason` String,
# )
# ENGINE = ReplacingMergeTree
# ORDER BY (`channel`, `timestamp`, `version`)
# PARTITION BY (`channel`, `is deleted`)
connection.query("SELECT * FROM `channels`.`messages` LIMIT 2") # OK
try:
    connection.query("SELECT * FROM `channels`.`messages` LIMIT 3") # Socket error
except Exception:
    connection.query("SELECT * FROM `channels`.`messages` LIMIT 1") # OK
```
### Steps to reproduce
1. import ClickHouse
2. call `get_client` (?)

### Expected behaviour
Object will be created to work with CH

### Code example
```python
import clickhouse_connect

connection = clickhouse_connect.get_client(
    host="192.168.196.66",
    compress=False,
    username="develop",
    secure=False,
)
```

### clickhouse-connect and/or ClickHouse server logs
Full server logs on [file](https://github.com/ClickHouse/clickhouse-connect/files/14735127/ch.log).

#### Environment
* clickhouse-connect version: 0.7.3
* Python version: 3.12
* Operating system: Windows 10

#### ClickHouse server
* ClickHouse Server version: 24.2.2.71
* ClickHouse OS: Ubuntu 22.04.4 LTS on Linux DESKTOP-L40U8AH 5.15.146.1-microsoft-standard-WSL2 #1 SMP Thu Jan 11 04:09:03 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
* ClickHouse Server non-default settings, if any: Listening to an external address on VPN network
* `CREATE TABLE` statements for tables involved:
System table: `system.settings`
* Sample data for these tables, use [clickhouse-obfuscator]:
On system table (`LIMIT 5`)
```
|           name            |    value     |  readonly  |
|:-------------------------:|:------------:|:----------:|
|          dialect          |  clickhouse  |     0      |
|  min_compress_block_size  |    65536     |     0      |
|  max_compress_block_size  |   1048576    |     0      |
|      max_block_size       |    65409     |     0      |
|   max_insert_block_size   |   1048449    |     0      |
```

**Comment by mister-proger** [comment]
At the same time, the selection using the `clickhouse-client` utility is error-free and visually instantaneous.

**Comment by mister-proger** [comment]
(The pull request that was mentioned - apparently by accident, I didn't do it)

**Comment by genzgd** [comment]
Can you curl your ClickHouse server HTTP port successfully?  This will run the system settings query:

```
curl 'http://localhost:8123/?query=SELECT%20*%20FROM%20system.settings'
```

It looks like there is something in your setup that does not like HTTP connections, and the data limit you see might be the amount of data that can fit in a single TCP packet.

PSQL and ClickHouse client both communicate over low level TCP protocol, so they wouldn't be affected by HTTP proxies or settings.

**Comment by genzgd** [comment]
As far as ClickHouse is concerned, the query worked fine:

```
2024.03.24 13:15:47.643576 [ 211251 ] {} <Trace> HTTPHandler-factory: HTTP Request for HTTPHandler-factory. Method: POST, Address: 192.168.196.125:53970, User-Agent: clickhouse-connect/0.7.3 (lv:py/3.11.6; os:win32), Length: 88, Content Type: text/plain; charset=utf-8, Transfer Encoding: identity, X-Forwarded-For: (none)
2024.03.24 13:15:47.643767 [ 211251 ] {} <Trace> DynamicQueryHandler: Request URI: /?wait_end_of_query=1
2024.03.24 13:15:47.643833 [ 211251 ] {} <Debug> HTTP-Session: 3127dcf2-d84a-4654-9d7e-42f52fc62617 Authenticating user 'develop' from 192.168.196.125:53970
2024.03.24 13:15:47.643872 [ 211251 ] {} <Debug> HTTP-Session: 3127dcf2-d84a-4654-9d7e-42f52fc62617 Authenticated with global context as user 4443dc7d-3d90-2b83-de14-5d1d9b4eff8b
2024.03.24 13:15:47.643914 [ 211251 ] {} <Debug> HTTP-Session: 3127dcf2-d84a-4654-9d7e-42f52fc62617 Creating session context with user_id: 4443dc7d-3d90-2b83-de14-5d1d9b4eff8b
2024.03.24 13:15:47.644001 [ 211251 ] {} <Trace> HTTP-Session: 3127dcf2-d84a-4654-9d7e-42f52fc62617 Creating query context from session context, user_id: 4443dc7d-3d90-2b83-de14-5d1d9b4eff8b, parent context user: develop
2024.03.24 13:15:47.644269 [ 211251 ] {a5a8dce2-3589-48ac-b4e6-fce80857e0c6} <Debug> executeQuery: (from 192.168.196.125:53970, user: develop) SELECT name, value, readonly as readonly FROM system.settings LIMIT 10000 FORMAT Native (stage: Complete)
2024.03.24 13:15:47.644608 [ 211251 ] {a5a8dce2-3589-48ac-b4e6-fce80857e0c6} <Trace> ContextAccess (develop): Access granted: SELECT(name, value, readonly) ON system.settings
2024.03.24 13:15:47.645912 [ 211251 ] {a5a8dce2-3589-48ac-b4e6-fce80857e0c6} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2024.03.24 13:15:47.646990 [ 211251 ] {a5a8dce2-3589-48ac-b4e6-fce80857e0c6} <Debug> executeQuery: Read 982 rows, 210.03 KiB in 0.002805 sec., 350089.1265597148 rows/sec., 73.12 MiB/sec.
2024.03.24 13:15:47.647565 [ 211251 ] {a5a8dce2-3589-48ac-b4e6-fce80857e0c6} <Debug> DynamicQueryHandler: Done processing query
2024.03.24 13:15:47.647745 [ 211251 ] {} <Debug> HTTP-Session: 3127dcf2-d84a-4654-9d7e-42f52fc62617 Logout, user_id: 4443dc7d-3d90-2b83-de14-5d1d9b4eff8b
```

So something between your client and ClickHouse is closing/resetting the connection?

**Comment by mister-proger** [comment]
Requests from my laptop (both from Windows and Linux to WSL) to `localhost` worked fine. However, from the same device to the IP in our VPN network, it was refused.

Interestingly, my test script also failed to give more than ~2000 bytes.

I think I'll ask my VPN a few questions. But maybe CH has any settings that can cause this behavior? Can you please tell me?

**Comment by genzgd** [comment]
No, as far as ClickHouse is concerned, the request succeeded and the full amount of data was sent over HTTP (if there was any limit in ClickHouse, it would have just sent that limited data instead of there being a connection reset).  It seems to be something between your client and your ClickHouse server.
