### ISSUE TITLE
sqlalchemy table reflection doesn't work for Point data type

### ISSUE THREAD

**Issue by Hexta** [ClickHouse/clickhouse-connect#332]
### Describe the bug

SQLAlchemy can't inspect tables with `Point` columns.
It affects Apache Superset: users can't sync columns from source.

### Steps to reproduce
1. Create a table with Point column.
2. Inspect table columns.
  a. Use the following code snippet. 
  b. Use Apache Superset
    1. Datasets -> [DS name] -> Edit -> Columns -> Sync columns from source.

### Code example
```python
from sqlalchemy import create_engine, inspect

conn = create_engine(DSN, echo=True)
insp = inspect(conn)
insp.get_columns(table, db)
```

### clickhouse-connect logs
```plain
/Users/xxx/work/src/venv/3.10/bin/python3.10 /Users/xxx/work/src/ch-connect/main.py 
2024-04-01 23:26:58,764 INFO sqlalchemy.engine.Engine DESCRIBE TABLE `db`.`table`
2024-04-01 23:26:58,765 INFO sqlalchemy.engine.Engine [raw sql] {}
Traceback (most recent call last):
  File "/Users/xxx/work/src/ch-connect/main.py", line 6, in <module>
    insp.get_columns('table', 'db')
  File "/Users/xxx/work/src/venv/3.10/lib/python3.10/site-packages/clickhouse_connect/cc_sqlalchemy/inspector.py", line 43, in get_columns
    sqla_type = sqla_type_from_name(row.type.replace('\n', ''))
  File "/Users/xxx/work/src/venv/3.10/lib/python3.10/site-packages/clickhouse_connect/cc_sqlalchemy/datatypes/base.py", line 135, in sqla_type_from_name
    return type_cls.build(type_def)
  File "/Users/xxx/work/src/venv/3.10/lib/python3.10/site-packages/clickhouse_connect/cc_sqlalchemy/datatypes/base.py", line 47, in build
    return cls._instance_cache.setdefault(type_def, cls(type_def=type_def))
TypeError: unhashable type: 'list'
```

### Apache Superset logs
```plain
2024-04-01 19:15:27,959:ERROR:superset.views.base:unhashable type: 'list'
Traceback (most recent call last):
  File "/app/superset/views/base.py", line 252, in wraps
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/flask_appbuilder/api/__init__.py", line 182, in wraps
    return f(self, *args, **kwargs)
  File "/app/superset/views/datasource/views.py", line 176, in external_metadata_by_name
    external_metadata = datasource.external_metadata()
  File "/app/superset/connectors/sqla/models.py", line 1323, in external_metadata
    return get_physical_table_metadata(
  File "/app/superset/connectors/sqla/utils.py", line 67, in get_physical_table_metadata
    cols = database.get_columns(table_name, schema=_schema_name)
  File "/app/superset/models/core.py", line 847, in get_columns
    return self.db_engine_spec.get_columns(
  File "/app/superset/db_engine_specs/base.py", line 1343, in get_columns
    cast(list[SQLAColumnType], inspector.get_columns(table_name, schema))
  File "/usr/local/lib/python3.9/site-packages/clickhouse_connect/cc_sqlalchemy/inspector.py", line 43, in get_columns
    sqla_type = sqla_type_from_name(row.type.replace('\n', ''))
  File "/usr/local/lib/python3.9/site-packages/clickhouse_connect/cc_sqlalchemy/datatypes/base.py", line 135, in sqla_type_from_name
    return type_cls.build(type_def)
  File "/usr/local/lib/python3.9/site-packages/clickhouse_connect/cc_sqlalchemy/datatypes/base.py", line 47, in build
    return cls._instance_cache.setdefault(type_def, cls(type_def=type_def))
TypeError: unhashable type: 'list'
```

#### Environment
* clickhouse-connect version: 0.7.5
* Python version: 3.10 & 3.9
* sqlalchemy: 1.4

#### ClickHouse server
* ClickHouse Server version: 23.12.5
* `CREATE TABLE` statements for tables involved:
```sql
CREATE TABLE db.table (`location` Point) ENGINE = MergeTree
```

**Comment by genzgd** [comment]
Thanks for the report!  It should be fixed in 0.7.6.
