### ISSUE TITLE
format_query_value for list of integers/floats broken since 0.7.5

### ISSUE THREAD

**Issue by icemac** [ClickHouse/clickhouse-connect#335]
### Steps to reproduce
1. python3.11 -m venv cl
2. cd cl
3. bin/pip install clickhouse_connect
4. bin/python

### Expected behaviour

Return a formatted query value, but raises an exception.
This worked fine until 0.7.4.
I think it got broken by https://github.com/ClickHouse/clickhouse-connect/pull/329

### Code example
```python
from clickhouse_connect.driver.query import format_query_value
format_query_value([1, 2, 3.14])
```

Result:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/.../python3.11/site-packages/clickhouse_connect/driver/query.py", line 402, in format_query_value
    return f"[{', '.join(format_query_value(x, server_tz) for x in value)}]"
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: sequence item 0: expected str instance, int found
```

#### Environment
* clickhouse-connect version: 0.7.6
* Python version: 3.11
* Operating system: MacOS Sonoma 14.4.1

**Comment by icemac** [comment]
Thank you for the quick fix.
