### ISSUE TITLE
ValueError: invalid literal for int() with base 16: for UUID LowCardinality column

### ISSUE THREAD

**Issue by Bikbai** [ClickHouse/clickhouse-connect#368]
### Code example
1. Step one:
Create table:
`CREATE TABLE dm.LowCard(
dt_column date,
lowcardcolumn LowCardinality(UUID)) engine=MergeTree() 
ORDER BY dt_column`
2. Python code:

```
import clickhouse_connect
from datetime import date
client = clickhouse_connect.get_client(host='server')

ctx = client.create_insert_context(
    table='LowCard',
    database='dm',
    column_names=['dt_column', 'lowcardcolumn'],
    data=([date(2024, 1, 1), '80397B00-E0B2-48AF-AF34-AE11A5546A3B'],
          [date(2024, 1, 1), '70397B00-E0B2-48AF-AF34-AE11A5546A3B'])
)
client.data_insert(ctx)
```

### Expected behaviour
Code executed like in SQL:
`insert into dm.LowCard (dt_column, lowcardcolumn) values('2024-01-01', 'C56ED18D-F879-47A3-B394-0EBC72534DD7')`

### Traceback:
```
Traceback (most recent call last):
  File ".\clickhouse-loader.py", line 42, in <module>
    client.data_insert(ctx)
  File ".\venv\lib\site-packages\clickhouse_connect\driver\httpclient.py", line 256, in data_insert
    response = self._raw_request(block_gen, params, headers, error_handler=error_handler, server_wait=False)
  File ".\venv\lib\site-packages\clickhouse_connect\driver\httpclient.py", line 440, in _raw_request
    error_handler(response)
  File ".\venv\lib\site-packages\clickhouse_connect\driver\httpclient.py", line 241, in error_handler
    raise ex
  File ".\venv\lib\site-packages\clickhouse_connect\driver\transform.py", line 104, in chunk_gen
    col_type.write_column(data, output, context)
  File ".\venv\lib\site-packages\clickhouse_connect\datatypes\base.py", line 202, in write_column
    self.write_column_data(column, dest, ctx)
  File ".\venv\lib\site-packages\clickhouse_connect\datatypes\base.py", line 213, in write_column_data
    self._write_column_low_card(column, dest, ctx)
  File ".\venv\lib\site-packages\clickhouse_connect\datatypes\base.py", line 275, in _write_column_low_card
    self._write_column_binary(index, dest, ctx)
  File ".\venv\lib\site-packages\clickhouse_connect\datatypes\special.py", line 45, in _write_column_binary
    x = int(v, 16)
ValueError: invalid literal for int() with base 16: '80397B00-E0B2-48AF-AF34-AE11A5546A3B'
```

**Comment by genzgd** [comment]
It looks like `clickhouse-connect` only accepts UUID strings without dashes at the moment.  You can work around that temporarily by removing the dashes, but I think it makes sense to automatically do that in the library.
