### ISSUE TITLE
Unable to insert unix timestamp in nanos into DateTime64(9) column by means of insert_file

### ISSUE THREAD

**Issue by szhem** [ClickHouse/clickhouse-connect#422]
### Describe the bug

Unable to insert unix timestamp in nanos into DateTime64(9) column starting from 0.8.0 version.
Latest 0.7.19 works as expected.

### Steps to reproduce
1. Create a table
```sql
CREATE TABLE t_ts_table
(
    `ts_ns` DateTime64(9) DEFAULT 0 CODEC(Delta(8), ZSTD)
)
ENGINE = MergeTree
PARTITION BY toYYYYMMDD(ts_ns)
ORDER BY ts_ns
```
2. Create file records.tsv with the following content

```
ts_ns
1731005237777063540
1731005237777063541
```

3. Try to insert a value into in using clickhouse_connect 0.8.0+ 

```bash
$ python insert_file.py
Traceback (most recent call last):
  File "ch_connect/insert_file.py", line 6, in <module>
    insert_file(c, table='t_ts_table', file_path='records.tsv', fmt='TSVWithNames')
  File "ch_connect/ch_connect.venv/lib/python3.12/site-packages/clickhouse_connect/driver/tools.py", line 28, in insert_file
    return client.raw_insert(full_table,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "ch_connect/ch_connect.venv/lib/python3.12/site-packages/clickhouse_connect/driver/httpclient.py", line 299, in raw_insert
    response = self._raw_request(insert_block, params, headers, server_wait=False)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "ch_connect/ch_connect.venv/lib/python3.12/site-packages/clickhouse_connect/driver/httpclient.py", line 461, in _raw_request
    self._error_handler(response)
  File "ch_connect/ch_connect.venv/lib/python3.12/site-packages/clickhouse_connect/driver/httpclient.py", line 384, in _error_handler
    raise OperationalError(err_str) if retried else DatabaseError(err_str) from None
clickhouse_connect.driver.exceptions.DatabaseError: HTTPDriver for http://localhost:8123 received ClickHouse error code 41
 Code: 41. DB::Exception: Cannot read DateTime: unexpected number of decimal digits: 19: (at row 1)
:
Row 1:
Column 0,   name: ts_ns, type: DateTime64(9), parsed text: "1731005237777063540"ERROR
Code: 41. DB::Exception: Cannot read DateTime: unexpected number of decimal digits: 19. (CANNOT_PARSE_DATETIME) (version 24.6.2.17 (official build))
```

### Expected behaviour

The same as with clickhouse connect 0.7.19 - all the entries from the file are inserted into a table

```bash
$ python insert_file.py
```
```
94f2eb9b744c :) select * from t_ts_table

SELECT *
FROM t_ts_table

Query id: 0cc2a73b-02b0-4ddb-9a1b-1fcf9aa2faa5

   ┌─────────────────────────ts_ns─┐
1. │ 2024-11-07 18:47:17.777063540 │
2. │ 2024-11-07 18:47:17.777063541 │
   └───────────────────────────────┘

2 rows in set. Elapsed: 0.002 sec.

```

### Code example
```python
import clickhouse_connect
from clickhouse_connect.driver.tools import insert_file

if __name__ == '__main__':
    c = clickhouse_connect.get_client(host='localhost', port=8123, username='clickhouse', password='clickhouse', database='default')
    insert_file(c, table='t_ts_table', file_path='records.tsv', fmt='TSVWithNames')
```

#### ClickHouse Server logs
```
2024.11.09 13:43:24.118489 [ 50 ] {bbc21df6-36f5-4161-a508-5aa21a350c82} <Error> DynamicQueryHandler: Code: 41. DB::Exception: Cannot read DateTime: unexpected number of decimal digits: 19: (at row 1)
:
Row 1:
Column 0,   name: ts_ns, type: DateTime64(9), parsed text: "1731005237777063540"ERROR
Code: 41. DB::Exception: Cannot read DateTime: unexpected number of decimal digits: 19. (CANNOT_PARSE_DATETIME) (version 24.6.2.17 (official build))

: While executing ParallelParsingBlockInputFormat. (CANNOT_PARSE_DATETIME), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000c3b2a28
1. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x0000000007bb443c
2. DB::Exception::Exception<unsigned long&>(int, FormatStringHelperImpl<std::type_identity<unsigned long&>::type>, unsigned long&) @ 0x0000000007cc97d8
3. auto void DB::(anonymous namespace)::parseDateTimeBestEffortImpl<void, false>(long&, DB::ReadBuffer&, DateLUTImpl const&, DateLUTImpl const&, DB::(anonymous namespace)::DateTimeSubsecondPart*)::'lambda'<typename ...$T>(int, FormatStringHelperImpl<std::type_identity<$T>::type...>, $T&&...)::operator()<unsigned long&>(int, FormatStringHelperImpl<std::type_identity<$T>::type...>, $T&&...) const @ 0x000000000c436fd8
4. void DB::(anonymous namespace)::parseDateTimeBestEffortImpl<void, false>(long&, DB::ReadBuffer&, DateLUTImpl const&, DateLUTImpl const&, DB::(anonymous namespace)::DateTimeSubsecondPart*) (.llvm.13685427944069632133) @ 0x000000000c42f904
5. DB::parseDateTime64BestEffort(DB::DateTime64&, unsigned int, DB::ReadBuffer&, DateLUTImpl const&, DateLUTImpl const&) @ 0x000000000c436a18
6. DB::SerializationDateTime64::deserializeTextEscaped(DB::IColumn&, DB::ReadBuffer&, DB::FormatSettings const&) const @ 0x000000000f69c308
7. DB::TabSeparatedFormatReader::readField(DB::IColumn&, std::shared_ptr<DB::IDataType const> const&, std::shared_ptr<DB::ISerialization const> const&, bool, String const&) @ 0x0000000011515b8c
8. DB::RowInputFormatWithNamesAndTypes::readRow(std::vector<COW<DB::IColumn>::mutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::mutable_ptr<DB::IColumn>>>&, DB::RowReadExtension&) @ 0x00000000113b7680
9. DB::IRowInputFormat::read() @ 0x000000001139b9f0
10. DB::IInputFormat::generate() @ 0x000000001134aa40
11. DB::ISource::tryGenerate() @ 0x000000001132cdac
12. DB::ISource::work() @ 0x000000001132c814
13. void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<DB::ParallelParsingInputFormat::scheduleParserThreadForUnitWithNumber(unsigned long)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x00000000114822d8
14. ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::worker(std::__list_iterator<ThreadFromGlobalPoolImpl<false, true>, void*>) @ 0x000000000c454864
15. void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x000000000c4583d0
16. void* std::__thread_proxy[abi:v15000]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>>(void*) @ 0x000000000c457080
17. start_thread @ 0x0000000000007624
18. ? @ 0x00000000000d162c
 (version 24.6.2.17 (official build))
```

#### ClickHouse Connect Logs:
```
Traceback (most recent call last):
  File "ch_connect/insert_file.py", line 6, in <module>
    insert_file(c, table='t_ts_table', file_path='records.tsv', fmt='TSVWithNames')
  File "ch_connect/ch_connect.venv/lib/python3.12/site-packages/clickhouse_connect/driver/tools.py", line 28, in insert_file
    return client.raw_insert(full_table,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "ch_connect/ch_connect.venv/lib/python3.12/site-packages/clickhouse_connect/driver/httpclient.py", line 299, in raw_insert
    response = self._raw_request(insert_block, params, headers, server_wait=False)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "ch_connect/ch_connect.venv/lib/python3.12/site-packages/clickhouse_connect/driver/httpclient.py", line 461, in _raw_request
    self._error_handler(response)
  File "ch_connect/ch_connect.venv/lib/python3.12/site-packages/clickhouse_connect/driver/httpclient.py", line 384, in _error_handler
    raise OperationalError(err_str) if retried else DatabaseError(err_str) from None
clickhouse_connect.driver.exceptions.DatabaseError: HTTPDriver for http://localhost:8123 received ClickHouse error code 41
 Code: 41. DB::Exception: Cannot read DateTime: unexpected number of decimal digits: 19: (at row 1)
:
Row 1:
Column 0,   name: ts_ns, type: DateTime64(9), parsed text: "1731005237777063540"ERROR
Code: 41. DB::Exception: Cannot read DateTime: unexpected number of decimal digits: 19. (CANNOT_PARSE_DATETIME) (version 24.6.2.17 (official build))
```

#### Environment
* clickhouse-connect version: 0.8.6
* Python version: 3.12.1
* Operating system: macOS 15.1 / Rocky Linux 9.1

#### ClickHouse server
* ClickHouse Server version: 24.6.2.17
* ClickHouse Server non-default settings, if any:
* `CREATE TABLE` statements for tables involved:
```sql
CREATE TABLE t_ts_table
(
    `ts_ns` DateTime64(9) DEFAULT 0 CODEC(Delta(8), ZSTD)
)
ENGINE = MergeTree
PARTITION BY toYYYYMMDD(ts_ns)
ORDER BY ts_ns
```
* Sample data for these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary

**Comment by genzgd** [comment]
Can you disable compression?

**Comment by szhem** [comment]
@genzgd Does not work with either disable or enabled compression.

**Comment by genzgd** [comment]
So this required some digging, but the problem is that `clickhouse-connect` 0.8.x automatically uses the query settings `date_time_input_format=best_effort`.  This was added to do correct parameter parsing for bound parameters.  It has the unintended side effect of breaking pure "number" input values for DateTime64 as you observed.

I think this behavior should be considered a bug and I'll look at filing an issue in the main CilckHouse project.  In the meantime the workaround is to send "basic" value for the `date_time_input_format` settings, like so:

```python
insert_file(client, 't_ts_table', 'date64.tsv', fmt='TSVWithNames',settings={'date_time_input_format':'basic'})
```

My apologies for breaking backward compatibility, but I find ClickHouse's behavior in this case very unintuitive.

**Comment by genzgd** [comment]
Okay, I think the reason this works is because when you use `date_time_input_format=basic`, the 19 digit numeric value is converted an Int64 value, which is how it is successfully inserted into the DateTime64 column (which is just an alias for an Int64 value).  If you use `date_time_input_format=best_effort`, the TSV value is considered a String, and can't be currently parsed by ClickHouse as nanoseconds.

So I don't think it's a good idea to change this behavior, because in many cases TSV or CSV values will use string formats like ISO8601.  In your particular use case I think you have to override the default setting as described in the previous comment.

**Comment by szhem** [comment]
with `date_time_input_format=basic` everything works as expected. Thanks a lot!
