### ISSUE TITLE
Inserting a date returns an error

### ISSUE THREAD

**Issue by pmusa** [ClickHouse/clickhouse-connect#423]
### Describe the bug
When trying to insert a date using the library, it returns the following error:

### Steps to reproduce
```
import clickhouse_connect

client = clickhouse_connect.get_client(
    host='',
    user='default',
    password='',
    secure=True
)

# Create table with one string column
client.command("""
    CREATE OR REPLACE TABLE lms.test (
        my_string String,
        my_number UInt8,
        my_date Date
    ) ENGINE = MergeTree() ORDER BY tuple()
""")


# Insert one sample row
client.insert(
    'lms.test',
    [['Hello, ClickHouse!', 8, '2024-01-01']],
    column_names=['my_string', 'my_number', 'my_date']
)
```

### Expected behaviour

It should just work 

### clickhouse-connect and/or ClickHouse server logs
```
Error serializing column `my_date` into data type `Date`
Traceback (most recent call last):
  File "/Users/pmusa/Coding/python-venv/lib/python3.12/site-packages/clickhouse_connect/driver/transform.py", line 104, in chunk_gen
    col_type.write_column(data, output, context)
  File "/Users/pmusa/Coding/python-venv/lib/python3.12/site-packages/clickhouse_connect/datatypes/base.py", line 202, in write_column
    self.write_column_data(column, dest, ctx)
  File "/Users/pmusa/Coding/python-venv/lib/python3.12/site-packages/clickhouse_connect/datatypes/base.py", line 217, in write_column_data
    self._write_column_binary(column, dest, ctx)
  File "/Users/pmusa/Coding/python-venv/lib/python3.12/site-packages/clickhouse_connect/datatypes/temporal.py", line 47, in _write_column_binary
    column = [(x - esd).days for x in column]
               ~~^~~~~
TypeError: unsupported operand type(s) for -: 'str' and 'datetime.date'
Traceback (most recent call last):
  File "/Users/pmusa/Coding/clickhouse/training/analytics/scripts/import clickhouse_connect.py", line 21, in <module>
    client.insert(
  File "/Users/pmusa/Coding/python-venv/lib/python3.12/site-packages/clickhouse_connect/driver/client.py", line 609, in insert
    return self.data_insert(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pmusa/Coding/python-venv/lib/python3.12/site-packages/clickhouse_connect/driver/httpclient.py", line 255, in data_insert
    response = self._raw_request(block_gen, params, headers, error_handler=error_handler, server_wait=False)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pmusa/Coding/python-venv/lib/python3.12/site-packages/clickhouse_connect/driver/httpclient.py", line 436, in _raw_request
    error_handler(response)
  File "/Users/pmusa/Coding/python-venv/lib/python3.12/site-packages/clickhouse_connect/driver/httpclient.py", line 240, in error_handler
    raise ex
  File "/Users/pmusa/Coding/python-venv/lib/python3.12/site-packages/clickhouse_connect/driver/transform.py", line 104, in chunk_gen
    col_type.write_column(data, output, context)
  File "/Users/pmusa/Coding/python-venv/lib/python3.12/site-packages/clickhouse_connect/datatypes/base.py", line 202, in write_column
    self.write_column_data(column, dest, ctx)
  File "/Users/pmusa/Coding/python-venv/lib/python3.12/site-packages/clickhouse_connect/datatypes/base.py", line 217, in write_column_data
    self._write_column_binary(column, dest, ctx)
  File "/Users/pmusa/Coding/python-venv/lib/python3.12/site-packages/clickhouse_connect/datatypes/temporal.py", line 47, in _write_column_binary
    column = [(x - esd).days for x in column]
               ~~^~~~~
TypeError: unsupported operand type(s) for -: 'str' and 'datetime.date'
```

#### Environment
* clickhouse-connect version: 0.7.8
* Python version: Python 3.12.7 (main, Oct  1 2024, 02:05:46) [Clang 15.0.0 (clang-1500.3.9.4)] on darwin
* Operating system: MacOS

#### ClickHouse server
ClickHouse Cloud 24.6.1.4609

**Comment by genzgd** [comment]
The library doesn't automatically parse string values as dates (or date times), since there are many possible formats and determining the input string format and parsing to dates is expensive.

Accordingly, when inserting data, `clickhouse-connect` can recognize Python `datetime.date` and `datetime.datetime` values, and integer values that match the internal ClickHouse date value (days since Jan 1, 1970).  Otherwise it is the caller's responsibility to convert the insert data into ones of those formats.
